language_map = {
    "js": "node {fileName}",
    "javascript": "node {fileName}",
    "java": "cd {dir} && javac {fileName} && java {fileNameWithoutExt}",
    "c": "cd {dir} && gcc {fileName} -o {fileNameWithoutExt} && {dir}{fileNameWithoutExt}",
    "cpp": "cd {dir} && g++ {fileName} -o {fileNameWithoutExt} && {dir}{fileNameWithoutExt}",
    "objective-c": "cd {dir} && gcc -framework Cocoa {fileName} -o {fileNameWithoutExt} && {dir}{fileNameWithoutExt}",
    "php": "php {fileName}",
    "py": "python -u {fileName}",
    "python": "python -u {fileName}",
    "perl": "perl {fileName}",
    "perl6": "perl6 {fileName}",
    "ruby": "ruby {fileName}",
    "go": "go run {fileName}",
    "lua": "lua {fileName}",
    "groovy": "groovy {fileName}",
    "powershell": "powershell -ExecutionPolicy ByPass -File {fileName}",
    "bat": "cmd /c {fileName}",
    "sh": "sh {fileName}",
    "bash": "bash {fileName}",
    "fsharp": "fsi {fileName}",
    "csharp": "scriptcs {fileName}",
    "vbscript": "cscript //Nologo {fileName}",
    "ts": "ts-node {fileName}",
    "typescript": "ts-node {fileName}",
    "coffeescript": "coffee {fileName}",
    "scala": "scala {fileName}",
    "swift": "swift {fileName}",
    "julia": "julia {fileName}",
    "crystal": "crystal {fileName}",
    "ocaml": "ocaml {fileName}",
    "r": "Rscript {fileName}",
    "applescript": "osascript {fileName}",
    "clojure": "lein exec {fileName}",
    "haxe": "haxe --cwd {dir}WithoutTrailingSlash --run {fileNameWithoutExt}",
    "rust": "cd {dir} && rustc {fileName} && {dir}{fileNameWithoutExt}",
    "racket": "racket {fileName}",
    "scheme": "csi -script {fileName}",
    "ahk": "autohotkey {fileName}",
    "autoit": "autoit3 {fileName}",
    "dart": "dart {fileName}",
    "pascal": "cd {dir} && fpc {fileName} && {dir}{fileNameWithoutExt}",
    "d": "cd {dir} && dmd {fileName} && {dir}{fileNameWithoutExt}",
    "haskell": "runhaskell {fileName}",
    "nim": "nim compile --verbosity:0 --hints:off --run {fileName}",
    "lisp": "sbcl --script {fileName}",
    "kit": "kitc --run {fileName}",
    "v": "v run {fileName}",
}
